USE db_ass
GO 

INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(2,2,202,'GOOD')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(5,4,402,'GOOD')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(6,5,506,'DAMAGED')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(7,6,103,'LOSS')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(8,9,204,'GOOD')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(9,1,307,'DAMAGED')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(3,3,108,'LOSS')