USE db_ass
GO 

INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(2,2,'101','GOOD')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(5,4,'103','GOOD')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(6,5,'203','DAMAGED')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(7,6,'402','LOSS')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(8,9,'204','GOOD')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(6,1,'307','DAMAGED')
INSERT INTO SUPPLY(SUPPLY_BRANCHID,SUPPLYID,SUPPLY_ROOMID,STATUSS) VALUES(3,3,'506','LOSS')