USE db_ass;
GO

INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Spencer Stokes','SpencerStokes@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Nettie Wood','NettieWood@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Kane Aguilar','KaneAguilar@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Lawrence Hood','LawrenceHood@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Kitty Duran','KittyDuran@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Floyd Huber','FloydHuber@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Rhea Gardner','RheaGardner@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Sid Watts','SidWatts@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Zac Richard','ZacRichard@gmail.com','None')
INSERT INTO SUPPLIER(SUPPLIER_NAME,SUPPLIER_EMAIL,SUPPLIER_ADDRES) VALUES('Curtis Allison','CurtisAllison@gmail.com','None')
