USE db_ass
GO 

INSERT INTO PROVIDE_SUPPLY(PROVIDE_SUPPLIER_ID,PROVIDE_SUPPLY_BRANCHID,PROVIDE_SUPPLYID) VALUES(4,5,4)
INSERT INTO PROVIDE_SUPPLY(PROVIDE_SUPPLIER_ID,PROVIDE_SUPPLY_BRANCHID,PROVIDE_SUPPLYID) VALUES(3,6,5)
INSERT INTO PROVIDE_SUPPLY(PROVIDE_SUPPLIER_ID,PROVIDE_SUPPLY_BRANCHID,PROVIDE_SUPPLYID) VALUES(5,7,6)
INSERT INTO PROVIDE_SUPPLY(PROVIDE_SUPPLIER_ID,PROVIDE_SUPPLY_BRANCHID,PROVIDE_SUPPLYID) VALUES(1,8,9)
INSERT INTO PROVIDE_SUPPLY(PROVIDE_SUPPLIER_ID,PROVIDE_SUPPLY_BRANCHID,PROVIDE_SUPPLYID) VALUES(6,9,1)