USE db_ass
GO 

INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,PACKAGE_CAPACITY,PACKAGE_COST) VALUES('LOVE YOU',37,2,1000)
INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,PACKAGE_CAPACITY,PACKAGE_COST) VALUES('WORKING LIKE A BEE',96,10,2000)
INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,PACKAGE_CAPACITY,PACKAGE_COST) VALUES('NEVER ALONE',25,4,1000)
INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,PACKAGE_CAPACITY,PACKAGE_COST) VALUES('HIGH TECH',34,2,2000)
INSERT INTO PACKAGE(PACKAGE_NAME,NUM_DAYS,PACKAGE_CAPACITY,PACKAGE_COST) VALUES('DRINK TILL DIE',82,3,3000)