USE db_ass;
GO

INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('3',2,'101')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('5',2,'103')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('6',6,'203')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('7',4,'302')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('8',7,'402')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('9',3,'506')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('2',5,'103')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('1',8,'204')
INSERT INTO HIRING_ROOM(HR_BOOKINGID,HR_BRANCHID,HR_ROOMID) VALUES('9',6,'307')
