USE db_ass;
GO

INSERT INTO SPA(SPA_NAME,SPA_SERVICEID) VALUES('SAKURA','DV1')
INSERT INTO SPA(SPA_NAME,SPA_SERVICEID) VALUES('BODY HOLIDAY','DV6')
INSERT INTO SPA(SPA_NAME,SPA_SERVICEID) VALUES('ANGEL SPA','DV11')
INSERT INTO SPA(SPA_NAME,SPA_SERVICEID) VALUES('CLUB DE NUIT','DV16')

