USE db_ass;
GO

INSERT INTO SOUVENIR(SOUVENIR_NAME,SERVICEID) VALUES('TOYS','DV3')
INSERT INTO SOUVENIR(SOUVENIR_NAME,SERVICEID) VALUES('CAKE','DV8')
INSERT INTO SOUVENIR(SOUVENIR_NAME,SERVICEID) VALUES('WATCH','DV13')
INSERT INTO SOUVENIR(SOUVENIR_NAME,SERVICEID) VALUES('CUP','DV18')