USE db_ass;
GO

INSERT INTO SOUVENIR_BRAND(BRAND,SBRAND_SERVICEID) VALUES('FANCYSHOP','DV3')
INSERT INTO SOUVENIR_BRAND(BRAND,SBRAND_SERVICEID) VALUES('SWEETSTORE','DV8')
INSERT INTO SOUVENIR_BRAND(BRAND,SBRAND_SERVICEID) VALUES('SMELL YOUR LIFE','DV13')
INSERT INTO SOUVENIR_BRAND(BRAND,SBRAND_SERVICEID) VALUES('HAVE A SIP','DV18')