USE db_ass;
GO

INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','Microsoft Corporation','DV1',2,26,20,3000,2)
INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','Amazon.com Inc.','DV2',3,30,26,2500,3)
INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','Alphabet Inc. Class A','DV4',4,26,29,2200,4)
INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','Facebook Inc. Class A','DV5',5,26,27,3400,5)
INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','Alphabet Inc. Class C','DV6',6,19,18,3700,6)
INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','Tesla Inc','DV7',7,16,24,4500,7)
INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','NVIDIA Corporation','DV8',8,30,24,4200,8)
INSERT INTO ESTATE(INFO,LINK,STORENAME,ESTATE_SERVICEID,ESTATEID,HEIGHT,WIDTH,COST,ESTATE_BRANCHID) VALUES('NONE','THIS IS A LINK','Berkshire Hathaway Inc. Class B','DV3',9,20,26,4100,9)
