USE db_ass;
GO

INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',2,2)
INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',3,3)
INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',4,4)
INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',5,5)
INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',6,6)
INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',7,7)
INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',8,8)
INSERT INTO TIME_ACTIVITY(AT_START_TIME,AT_END_TIME,AT_ID,AT_BRANCHID) VALUES('8:00','20:00',9,9)

