USE db_ass;
GO

INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE B',2)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE D',3)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE E',4)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE A',5)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE C',6)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE B',7)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE D',8)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE A',9)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE B',10)
INSERT INTO ZONES(ZNAME,ZONE_BRANCHID) VALUES('ZONE A',11)
