USE db_ass
GO

INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(1,'ZONE B')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(1,'ZONE C')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(2,'ZONE B')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(3,'ZONE D')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(4,'ZONE E')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(5,'ZONE A')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(6,'ZONE C')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(7,'ZONE B')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(8,'ZONE D')
INSERT INTO ZONES(ZONE_BRANCHID,ZNAME) VALUES(9,'ZONE A')