USE db_ass
GO

INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('STANDARD','75',2,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('MINIMALISTIC','82',3,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('DELUXE','91',5,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('STUDIO','102',5,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('CONNECTING','200',9,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('SUITES','105',5,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('JUNIOR SUITES','110',7,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('PRESIDENTIAL SUITES','150',8,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('PENTHOUSE SUITES','220',10,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('HONEYMOON SUITES','140',2,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('BRIDAL SUITES','160',2,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('APARTMENT','180',8,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('VILLAS','210',9,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('CABANAS','185',9,'None')
INSERT INTO ROOMTYPE(TYPENAME,AREA,CAPACITY,DESCRIPTIONS) VALUES('BUNGALOWS','240',10,'None')


