USE db_ass;
GO

INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('STANDARD','None',75,2)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('MINIMALISTIC','None',82,3)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('DELUXE','None',91,5)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('STUDIO','None',102,5)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('CONNECTING','None',200,7)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('SUITES','None',105,5)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('JUNIOR SUITES','None',110,7)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('PRESIDENTIAL SUITES','None',150,8)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('PENTHOUSE SUITES','None',220,10)
INSERT INTO ROOMTYPE(TYPENAME,DESCRIPTIONS,AREA,CAPACITY) VALUES('HONEYMOON SUITES','None',140,2)
