USE db_ass;
GO

INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('1',1.2,5.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('2',1.5,2.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('3',1.8,4.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('4',2.0,7.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('5',1.6,9.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('6',1.8,1.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('7',2.1,7.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('8',2.2,4.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('9',2.3,5.0)
INSERT INTO BEDINFO(BED_TYPEID,SIZE,QUANTITY) VALUES('10',2.4,5.0)

