USE db_ass
GO

INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(2,2,1000)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(2,1,2000)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(3,3,1500)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(4,4,2200)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(5,5,2500)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(6,6,2700)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(7,7,3000)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(8,2,3500)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(9,4,3200)
INSERT INTO BRANCH_HAVE_ROOMTYPE(BHR_BRANCHID,BHR_TYPEID,[PRICE (kVND)]) VALUES(10,1,3400)