USE db_ass
GO

INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE B','101',2,'2')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE B','103',2,'2')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE C','203',5,'6')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE E','302',7,'4')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE B','402',9,'7')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE D','506',10,'3')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE A','103',9,'5')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE D','204',7,'8')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE C','307',8,'6')
INSERT INTO ROOM(ROOM_ZNAME,ROOMID,ROOM_TYPEID,ROOM_BRANCHID) VALUES('ZONE B','605',9,'10')
