USE db_ass
GO

INSERT INTO SUPPLY_TYPE(SNAME) VALUES('LAMP')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('PILLOW')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('BEDDINGS')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('SHEETS')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('TABLE')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('CHAIR')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('MENU')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('GARBAGE BAGS')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('24 INCH TOWEL BAR')
INSERT INTO SUPPLY_TYPE(SNAME) VALUES('SHOWER CURTAIN')