USE db_ass
GO


SELECT * FROM BRANCH
SELECT * FROM BRANCH_IMG
SELECT * FROM ZONES
SELECT * FROM ROOMTYPE
SELECT * FROM BEDINFO
SELECT * FROM BRANCH_HAVE_ROOMTYPE
SELECT * FROM ROOM
SELECT * FROM SUPPLY_TYPE
SELECT * FROM SUPPLY_IN_ROOM
SELECT * FROM SUPPLY
SELECT * FROM SUPPLIER
SELECT * FROM PROVIDE_SUPPLY
SELECT * FROM CUSTOMER
SELECT * FROM PACKAGE
SELECT * FROM BILL_SERVICE
SELECT * FROM RECEIPT
SELECT * FROM HIRING_ROOM
SELECT * FROM COMPANY
SELECT * FROM SERVICES
SELECT * FROM SPA
SELECT * FROM SOUVENIR
SELECT * FROM SOUVENIR_BRAND
SELECT * FROM ESTATE
SELECT * FROM STORE_PIC
SELECT * FROM TIME_ACTIVITY